name: Build CI

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Versions
      run: |
        python3 --version
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install deps
      run: |
        pip install -r requirements.txt
        pip install circuitpython-build-tools Sphinx sphinx-rtd-theme
        pip install --force-reinstall pylint==1.9.2
    - name: CircuitPython version
      run: git describe --dirty --always --tags
    - name: PyLint
      run: |
        pylint adafruit_testrepo.py
        ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace examples/*.py)
    - name: Clone circuitpython-build-tools development
      run: |
        git clone https://github.com/sommersoft/circuitpython-build-tools.git
        git fetch
        git checkout origin/gh_actions
    - name: pip install development build-tools
      run: pip3 install -e ./circuitpython-build-tools
    - name: Build assets
      run: circuitpython-build-bundles --filename_prefix adafruit-circuitpython-testrepo --library_location .
