name: Build CI

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Translate Repo Name
      id: repo-name
      run: |
        echo ::set-output name=repo-name::$(
        echo ${{ github.repository }} |
        awk -F '\/' '{ print tolower($2) }' |
        tr '_' '-'
        )
    - name: Show Translated Repo Name
      run: |
        echo 'Translated: ${{ steps.repo-name.outputs.repo-name }}'
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Versions
      run: |
        python3 --version
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install deps
      run: |
        sudo apt-get install -y gettext
        pip install -r requirements.txt
        pip install circuitpython-build-tools Sphinx sphinx-rtd-theme
        pip install --force-reinstall pylint==1.9.2
    - name: Library version
      run: git describe --dirty --always --tags
    - name: PyLint
      run: |
        pylint adafruit_testrepo.py
        ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace examples/*.py)
    - name: Build assets
      run: circuitpython-build-bundles --filename_prefix adafruit-circuitpython-testrepo --library_location .
    - name: Build docs
      working-directory: docs
      run: sphinx-build -E -W -b html . _build/html
